### ISSUE TITLE
[Request a Test]: BRD

### ISSUE THREAD

**Issue by sbddesign** [sbddesign/bip21-site#26]
### App Name

BRD

### App Website

https://brd.com/

**Comment by emanuelb** [comment]
BRD is defunct wallet, was acquired by coinbase, latest version will ask user to migrate seed to another app, so if the wallet is checked older version should be used.
From https://brd.com/brd-joins-coinbase

> March 4, 2022 - Peer to peer transactions will be disabled; however, users will remain able to access their 12 word backup phrase for migration to the Coinbase Wallet app.

**Comment by sbddesign** [comment]
Thanks @emanuelb. If this project is shutting down, I don't see a need for testing it any longer. Closing this issue.
