### ISSUE TITLE
[Request a Test]: Kraken

### ISSUE THREAD

**Issue by sbddesign** [sbddesign/bip21-site#31]
### App Name

Kraken

### App Website

https://www.kraken.com/

**Comment by PierreRochard** [comment]
1. Both the mobile apps `Kraken` and `Kraken Pro` can scan a BIP21 QR code. The website does not have scanning functionality. 
2. Currently neither of the mobile apps recognize the lightning parameter in the BIP21 URI but the presence of the param does not cause an error.
3. The website and mobile apps do support creating a BIP21 QR code for deposits, but not with a lightning param.

**Comment by sbddesign** [comment]
Added in 23e25fe. Thanks @PierreRochard!
