### ISSUE TITLE
[Wallet Test]: Coinbase Wallet (non-custodial...not the "Coinbase" app which is custodial)

### ISSUE THREAD

**Issue by moneyball** [sbddesign/bip21-site#44]
### App Name

Coinbase Wallet

### App Website

iphone app store

### Scans BIP-21

Yes

### Recognize Lightning

No

### Creates BIP-21 QR codes

false

### Description

I don't know if it generates a BIP21 QR code.

**Comment by sbddesign** [comment]
Thanks! @moneyball does the Coinbase wallet support lightning in any form? If not, I'm going to mark it "N/A" for recognizes lightning.

**Comment by moneyball** [comment]
It does not support LN

**Comment by sbddesign** [comment]
Added this to the table in 4dff2a0
