### ISSUE TITLE
[Wallet Test]: BTCPay Server

### ISSUE THREAD

**Issue by pavlenex** [sbddesign/bip21-site#53]
### App Name

BTCPay Server

### App Website

http://btcpayserver.org

### Scans BIP-21

Yes

### Recognize Lightning

Not applicable - the wallet doesn't support Lightning

### Creates BIP-21 QR codes

I'm not sure

### Description

.

**Comment by sbddesign** [comment]
Hey @pavlenex @bitkarrot also did some thinking about this and we got this added in #56. Just to confirm, BTCPay does not have the capability of scanning, correct? The prime use case for BTCPay would be generating BIP21 QRs in a future where everyone supports it, am I right?

**Comment by pavlenex** [comment]
BTCPay does have a capability of scanning. It can generate and read bip21 qr's wallet doesn't generate unified qr, as it's on chain-wallet, but invoices can generate an unified qr.

![Screenshot 2022-03-25 at 14 30 53](https://user-images.githubusercontent.com/36959754/160130174-61af719b-3876-4907-9a77-599b3a39dcc7.png)

**Comment by pavlenex** [comment]
Correct on all.

> Are you saying that if the BTCPay store has lightning enabled, then it CAN generate a BIP21 with lightning included?

BTCPay has been supporting BIP21 with BOLT11 for over a year now, maybe even more, it's up to users to enable it, if enabled, then > yes.

![Screenshot 2022-03-25 at 19 03 21](https://user-images.githubusercontent.com/36959754/160176803-a03b55d4-634b-4f3c-9e14-541b10bbd8a6.png)
![Screenshot 2022-03-25 at 19 03 39](https://user-images.githubusercontent.com/36959754/160176811-29ef4243-0d15-45d9-a1c0-f474e6fdefc0.png)

**Comment by sbddesign** [comment]
Thanks! This has been added. @bitkarrot thank you for testing as well, I have updated the BTCPay entry with new guidance from @pavlenex.
