### ISSUE TITLE
[Wallet Test]: OpenNode

### ISSUE THREAD

**Issue by alexlwn123** [sbddesign/bip21-site#57]
### App Name

OpenNode

### App Website

opennode.com

### Scans BIP-21

Not applicable - this software doesn't scan QR codes

### Recognize Lightning

Not applicable - the wallet doesn't support Lightning

### Creates BIP-21 QR codes

Yes

### Description

# OpenNode 
[OpenNode](https://opennode.com) is a Lightning Payment Provider that allows merchants to accept bitcoin. For developers, they provide an API to generate and manage generic "charges" that can be paid over either a bitcoin transaction or a lightning invoice. 

---

From [OpenNode's docs](https://developers.opennode.com/docs/creating-a-charge)

Description of charges:
> You need to create a 'charge' to receive payments through OpenNode. A charge contains both a Lightning Network BOLT11 invoice, capable of accepting payments through the LN protocol, and a on-chain address for standard on-chain transactions.

Inclusion of BIP21 URIs: 
> If you want to build your own checkout experience you can create BIP21 + BOLT11 QR code using the uri field.

Charge object schema:
```json
{
    "data": {
        "id": "1543f881-5b86-46f0-b0ec-8f2d3a6b9498",
        "name": null,
        "description": "My test charge",
        "created_at": 1559566069,
        "status": "unpaid",
        "callback_url": "https://example.com/webhook/opennode",
        "success_url": "https://example.com/order/abc123",
        "order_id": "823320",
        "notes": "Order: 823320\nCustomer Email: N/A",
        "currency": "USD",
        "source_fiat_value": 10.5,
        "fiat_value": 10.5,
        "auto_settle": false,
        "notif_email": null,
        "lightning_invoice": {
            "expires_at": 1559569669,
            "payreq": "LNTB1230250N1PW029H4PP55A5L9MULUWDU9DF8R3JYAJTGL64YU60MRSLP98QZHDD9L29ZXE8SDQHF4UJQAR9WD6ZQCMGV9EXWEGCQZPG6G0SY8DDA8PV9HYJ65EXG9NENW0VCLELHNKN0TA20R03FVL6EK2NE7MNETPNDHWR0TMTXR6RCXA5AN6XY732RLZ6L23KHLGKW3Y4F7SPZR5Z5V"
        },
        "chain_invoice": {
            "address": "2NAVFQaNg2y3QAoh6nZ5WrvWpxp7YQ7Yaed"
        },
        "address": "2NAVFQaNg2y3QAoh6nZ5WrvWpxp7YQ7Yaed",
        "amount": 123025,
        "uri": "bitcoin:2NAVFQaNg2y3QAoh6nZ5WrvWpxp7YQ7Yaed?amount=0.00123025&label=My test charge&lightning=LNTB1230250N1PW029H4PP55A5L9MULUWDU9DF8R3JYAJTGL64YU60MRSLP98QZHDD9L29ZXE8SDQHF4UJQAR9WD6ZQCMGV9EXWEGCQZPG6G0SY8DDA8PV9HYJ65EXG9NENW0VCLELHNKN0TA20R03FVL6EK2NE7MNETPNDHWR0TMTXR6RCXA5AN6XY732RLZ6L23KHLGKW3Y4F7SPZR5Z5V"
    }
}  
```

**Comment by sbddesign** [comment]
Added to the site. Thanks @alexlwn123!
