### ISSUE TITLE
Use the standard for micropayments

### ISSUE THREAD

**Issue by RCasatta** [sbddesign/bip21-site#69]
I would like to show the unified QR but I don't want to fall back to onchain payment because the amount in my use case is too small.

According to bip21it isn't possible to avoid the bitcoin address, how is this use case handled?

**Comment by moneyball** [comment]
There's been recent discussion about this in the design community Slack: https://bitcoindesign.slack.com/archives/C01TTD8Q7ST/p1659463066895689

**Comment by RCasatta** [comment]
From the discussion for lightning-only payment I think I have to use `lightning:` URI as defined in https://github.com/lightning/bolts/blob/master/11-payment-encoding.md

Would have been better to cover also this case in the unified QR but I understand it clash with bip21 spec...
