### ISSUE TITLE
Electrum mobile

### ISSUE THREAD

**Issue by botnursery** [sbddesign/bip21-site#77]
Recognize but no lightning enabled

![Screenshot_2022-12-14-20-22-12-544_org electrum electrum](https://user-images.githubusercontent.com/54031418/207680527-df37980d-276c-4e25-9427-e4c267328a53.jpg)
![Screenshot_2022-12-14-20-26-41-123_org electrum electrum](https://user-images.githubusercontent.com/54031418/207680537-b74321ff-9eef-463c-938b-5fa260dfdc91.jpg)

**Comment by sbddesign** [comment]
@botnursery Thanks! When you say "Recognize but no lightning enabled", do you mean that Electrum mobile fails to recognize the `lightning` param, or are you saying that Electrum mobile is not a lightning wallet? I've never used it before, so that's why I am asking.

**Comment by botnursery** [comment]
I didn't go into detail and previously only used mobile Electrum for browsing.  Now I see that lightning payments have appeared.  When I tried to pay for the test QR, the wallet opened an ordinary on-chain payment.  But if I myself try to generate a Request, the wallet may generate a lightning-QR.  But what format it is not clear.

![Screenshot_2022-12-16-02-06-14-340_org electrum electrum](https://user-images.githubusercontent.com/54031418/207994038-6a801050-d59c-413b-ab35-4509854eef81.jpg)
![Screenshot_2022-12-16-01-15-24-256_org electrum electrum](https://user-images.githubusercontent.com/54031418/207994040-f901ecb5-e033-49be-9e83-122a34e1a0c8.jpg)

**Comment by sbddesign** [comment]
Ok, I think you are trying to say that *yes, the app does support lightning* but *no, it does not recognize the lightning param* when scanning the QR. Thanks.

**Comment by sbddesign** [comment]
Thanks @botnursery updated the site
