### ISSUE TITLE
[Wallet Test]: Exodus

### ISSUE THREAD

**Issue by juscamarena** [sbddesign/bip21-site#79]
### App Name

Exodus

### App Website

https://www.exodus.com/

### Scans BIP-21

Yes

### Recognize Lightning

No

### Creates BIP-21 QR codes

No (more common)

### Description

https://twitter.com/MichaelRihani/status/1555026695022731264?s=20&t=zDzAdL_pncYiRxD9hjrV6w

The wallet does not parse lightning param when scanning in lightning mode. It scans the on chain address when selecting bitcoin at least.

![IMG_5A0E0B9F593C-1](https://user-images.githubusercontent.com/446261/209254873-542f0f24-f2fb-476f-a5b6-a49f376bca62.jpeg)

**Comment by sbddesign** [comment]
Thanks @juscamarena!
